## Set input x as matrix
### Set solved value as i to denote the inverse of the matrix
### Followed same format as example provided using solve function and "i"

makeCacheMatrix <- function(x = matrix()) {
  i <- NULL
  set <- function(y) {
    x <<- y
    i <<- NULL
  }
  get <- function() x
  setsolve <- function(solve) i <<- solve
  getsolve <- function() i
  list(set = set, get = get,
       setsolve = setsolve,
       getsolve = getsolve)
}

## The makCacheSolve function creates a matrix object that can cache its inverse

cacheSolve <- function(x, ...) {
  i <- x$getsolve()
  if(!is.null(i)) {
    message("getting cached data")
    return(i)
  }
  data <- x$get()
  i <- solve(data, ...)
  x$setsolve(i)
  i
}

## The cacheSolve function takes the matrix object generated by the first function and returns its inverse either through calculation or by retrieving it from the cache

# Test functions

ExampleMatrix <- makeCacheMatrix(matrix(sample(1:200, 16), 4, 4))

ExampleMatrix$get()

ExampleMatrix$getsolve()

cacheSolve(ExampleMatrix)

cacheSolve(ExampleMatrix)

ExampleMatrix$setsolve()

ExampkeMatrix$set(matrix(1:4, 2, 2))

ExampleMatrix$get()

ExampleMatrix$getsolve()

cacheSolve(ExampleMatrix)

cacheSolve(ExampleMatrix)
